# Generated by Django 5.2.6 on 2025-10-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_account_created_by_alter_account_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name']},
        ),
    ]
