# Generated by Django 5.2.6 on 2025-10-12 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
