# Generated by Django 5.2.6 on 2025-10-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_category_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Outcome', 'Outcome'), ('Transfer', 'Transfer')], default='Outcome', max_length=10),
        ),
    ]
