# Generated by Django 5.2.6 on 2025-10-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
