# Generated by Django 5.2.6 on 2025-10-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_transaction_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
