# Generated by Django 5.2.6 on 2025-10-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_transaction_transfer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Outcome', 'Outcome'), ('Transfer', 'Transfer'), ('Transfer_from', 'Transfer_from'), ('Transfer_to', 'Transfer_to')], default='Outcome', max_length=20),
        ),
    ]
