# Generated by Django 5.2.6 on 2025-10-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Outcome', 'Outcome'), ('Transfer_from', 'Transfer_from'), ('Transfer_to', 'Transfer_to')], default='Outcome', max_length=20),
        ),
    ]
