# Generated by Django 5.2.6 on 2025-11-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='iban',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
