# Generated by Django 5.2.6 on 2025-12-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_account_iban'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='categories', to='finance.categorytag'),
        ),
    ]
