# Generated by Django 5.2.6 on 2025-12-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_categorytag_category_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='finance.categorytag'),
        ),
    ]
